version: "3"

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh node index.js
    networks:
      - node-network
    volumes:
      - ./node:/var/www/html
    tty: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    # volumes:
    #   - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: guilhermebiavati/nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"

networks:
  node-network:
    driver: bridge
